/**
 * Define marker data for each year
 */


var markers = [ {
  "year": 2007,
  "images": [{
      "imageURL": targetSVG,
      "title": "Vienna",
      "latitude": 48.2092,
      "longitude": 16.3728,
    }, {
      
      "title": "Minsk",
      "latitude": 53.9678,
      "longitude": 27.5766,
      
    }, {
      "imageURL": targetSVG,
      "title": "Brussels",
      "latitude": 50.8371,
      "longitude": 4.3676,
    }, {
      "imageURL": targetSVG,
      "title": "Sarajevo",
      "latitude": 43.8608,
      "longitude": 18.4214
    }, {
      "imageURL": targetSVG,
      "title": "Sofia",
      "latitude": 42.7105,
      "longitude": 23.3238
    }, {
      "imageURL": targetSVG,
      "title": "Zagreb",
      "latitude": 45.8150,
      "longitude": 15.9785
    }, {
      "imageURL": targetSVG,
      "title": "Pristina",
      "latitude": 42.666667,
      "longitude": 21.166667
    }, {
      "imageURL": targetSVG,
      "title": "Prague",
      "latitude": 50.0878,
      "longitude": 14.4205
    }, {
      "imageURL": targetSVG,
      "title": "Copenhagen",
      "latitude": 55.6763,
      "longitude": 12.5681
    }, {
      "imageURL": targetSVG,
      "title": "Tallinn",
      "latitude": 59.4389,
      "longitude": 24.7545
    }, {
      "imageURL": targetSVG,
      "title": "Helsinki",
      "latitude": 60.1699,
      "longitude": 24.9384
    }, {
      "imageURL": targetSVG,
      "title": "Paris",
      "latitude": 48.8567,
      "longitude": 2.3510
    }, {
      "imageURL": targetSVG,
      "title": "Berlin",
      "latitude": 52.5235,
      "longitude": 13.4115
    }, {
      "imageURL": targetSVG,
      "title": "Athens",
      "latitude": 37.9792,
      "longitude": 23.7166
    }, {
      "imageURL": targetSVG,
      "title": "Budapest",
      "latitude": 47.4984,
      "longitude": 19.0408
    }]
}, {
  "year": 2008,
  "images": [{
      "imageURL": targetSVG,
      "title": "Copenhagen",
      "latitude": 55.6763,
      "longitude": 12.5681
    }, {
      "imageURL": targetSVG,
      "title": "Tallinn",
      "latitude": 59.4389,
      "longitude": 24.7545
    }, {
      "imageURL": targetSVG,
      "title": "Helsinki",
      "latitude": 60.1699,
      "longitude": 24.9384
    }, {
      "imageURL": targetSVG,
      "title": "Paris",
      "latitude": 48.8567,
      "longitude": 2.3510
    }, {
      "imageURL": targetSVG,
      "title": "Berlin",
      "latitude": 52.5235,
      "longitude": 13.4115
    }, {
      "imageURL": targetSVG,
      "title": "Athens",
      "latitude": 37.9792,
      "longitude": 23.7166
    }, {
      "imageURL": targetSVG,
      "title": "Budapest",
      "latitude": 47.4984,
      "longitude": 19.0408
    }, {
      "imageURL": targetSVG,
      "title": "Reykjavik",
      "latitude": 64.1353,
      "longitude": -21.8952
    }, {
      "imageURL": targetSVG,
      "title": "Dublin",
      "latitude": 53.3441,
      "longitude": -6.2675
    }, {
      "imageURL": targetSVG,
      "title": "Rome",
      "latitude": 41.8955,
      "longitude": 12.4823
    }, {
      "imageURL": targetSVG,
      "title": "Riga",
      "latitude": 56.9465,
      "longitude": 24.1049
    }, {
      "imageURL": targetSVG,
      "title": "Vaduz",
      "latitude": 47.1411,
      "longitude": 9.5215
    }, {
      "imageURL": targetSVG,
      "title": "Vilnius",
      "latitude": 54.6896,
      "longitude": 25.2799
    }, {
      "imageURL": targetSVG,
      "title": "Luxembourg",
      "latitude": 49.6100,
      "longitude": 6.1296
    }, {
      "imageURL": targetSVG,
      "title": "Skopje",
      "latitude": 42.0024,
      "longitude": 21.4361
    } ]
}, {
  "year": 2009,
  "images": [{
      "imageURL": targetSVG,
      "title": "Dublin",
      "latitude": 53.3441,
      "longitude": -6.2675
    }, {
      "imageURL": targetSVG,
      "title": "Rome",
      "latitude": 41.8955,
      "longitude": 12.4823
    }, {
      "imageURL": targetSVG,
      "title": "Riga",
      "latitude": 56.9465,
      "longitude": 24.1049
    }, {
      "imageURL": targetSVG,
      "title": "Vaduz",
      "latitude": 47.1411,
      "longitude": 9.5215
    }, {
      "imageURL": targetSVG,
      "title": "Vilnius",
      "latitude": 54.6896,
      "longitude": 25.2799
    }, {
      "imageURL": targetSVG,
      "title": "Luxembourg",
      "latitude": 49.6100,
      "longitude": 6.1296
    }, {
      "imageURL": targetSVG,
      "title": "Skopje",
      "latitude": 42.0024,
      "longitude": 21.4361
    }, {
      "imageURL": targetSVG,
      "title": "Valletta",
      "latitude": 35.9042,
      "longitude": 14.5189
    }, {
      "imageURL": targetSVG,
      "title": "Chisinau",
      "latitude": 47.0167,
      "longitude": 28.8497
    }, {
      "imageURL": targetSVG,
      "title": "Monaco",
      "latitude": 43.7325,
      "longitude": 7.4189
    }, {
      "imageURL": targetSVG,
      "title": "Podgorica",
      "latitude": 42.4602,
      "longitude": 19.2595
    }, {
      "imageURL": targetSVG,
      "title": "Amsterdam",
      "latitude": 52.3738,
      "longitude": 4.8910
    }, {
      "imageURL": targetSVG,
      "title": "Oslo",
      "latitude": 59.9138,
      "longitude": 10.7387
    }, {
      "imageURL": targetSVG,
      "title": "Warsaw",
      "latitude": 52.2297,
      "longitude": 21.0122
    } ]
}, {
  "year": 2010,
  "images": [{
      "imageURL": targetSVG,
      "title": "Valletta",
      "latitude": 35.9042,
      "longitude": 14.5189
    }, {
      "imageURL": targetSVG,
      "title": "Chisinau",
      "latitude": 47.0167,
      "longitude": 28.8497
    }, {
      "imageURL": targetSVG,
      "title": "Monaco",
      "latitude": 43.7325,
      "longitude": 7.4189
    }, {
      "imageURL": targetSVG,
      "title": "Podgorica",
      "latitude": 42.4602,
      "longitude": 19.2595
    }, {
      "imageURL": targetSVG,
      "title": "Amsterdam",
      "latitude": 52.3738,
      "longitude": 4.8910
    }, {
      "imageURL": targetSVG,
      "title": "Oslo",
      "latitude": 59.9138,
      "longitude": 10.7387
    }, {
      "imageURL": targetSVG,
      "title": "Warsaw",
      "latitude": 52.2297,
      "longitude": 21.0122
    }, {
      "imageURL": targetSVG,
      "title": "Lisbon",
      "latitude": 38.7072,
      "longitude": -9.1355
    }, {
      "imageURL": targetSVG,
      "title": "Bucharest",
      "latitude": 44.4479,
      "longitude": 26.0979
    }, {
      "imageURL": targetSVG,
      "title": "Moscow",
      "latitude": 55.7558,
      "longitude": 37.6176
    }, {
      "imageURL": targetSVG,
      "title": "San Marino",
      "latitude": 43.9424,
      "longitude": 12.4578
    }, {
      "imageURL": targetSVG,
      "title": "Belgrade",
      "latitude": 44.8048,
      "longitude": 20.4781
    }, {
      "imageURL": targetSVG,
      "title": "Bratislava",
      "latitude": 48.2116,
      "longitude": 17.1547
    }, {
      "imageURL": targetSVG,
      "title": "Ljubljana",
      "latitude": 46.0514,
      "longitude": 14.5060
    }, {
      "imageURL": targetSVG,
      "title": "Madrid",
      "latitude": 40.4167,
      "longitude": -3.7033
    }]
}, {
  "year": 2011,
  "images": [{
      "imageURL": targetSVG,
      "title": "Lisbon",
      "latitude": 38.7072,
      "longitude": -9.1355
    }, {
      "imageURL": targetSVG,
      "title": "Bucharest",
      "latitude": 44.4479,
      "longitude": 26.0979
    }, {
      "imageURL": targetSVG,
      "title": "Moscow",
      "latitude": 55.7558,
      "longitude": 37.6176
    }, {
      "imageURL": targetSVG,
      "title": "San Marino",
      "latitude": 43.9424,
      "longitude": 12.4578
    }, {
      "imageURL": targetSVG,
      "title": "Belgrade",
      "latitude": 44.8048,
      "longitude": 20.4781
    }, {
      "imageURL": targetSVG,
      "title": "Bratislava",
      "latitude": 48.2116,
      "longitude": 17.1547
    }, {
      "imageURL": targetSVG,
      "title": "Ljubljana",
      "latitude": 46.0514,
      "longitude": 14.5060
    }, {
      "imageURL": targetSVG,
      "title": "Madrid",
      "latitude": 40.4167,
      "longitude": -3.7033
    }, {
      "imageURL": targetSVG,
      "title": "Stockholm",
      "latitude": 59.3328,
      "longitude": 18.0645
    }, {
      "imageURL": targetSVG,
      "title": "Bern",
      "latitude": 46.9480,
      "longitude": 7.4481
    }, {
      "imageURL": targetSVG,
      "title": "Kiev",
      "latitude": 50.4422,
      "longitude": 30.5367
    }, {
      "imageURL": targetSVG,
      "title": "London",
      "latitude": 51.5002,
      "longitude": -0.1262
    }, {
      "imageURL": targetSVG,
      "title": "Gibraltar",
      "latitude": 36.1377,
      "longitude": -5.3453
    }, {
      "imageURL": targetSVG,
      "title": "Saint Peter Port",
      "latitude": 49.4660,
      "longitude": -2.5522
    }, {
      "imageURL": targetSVG,
      "title": "Douglas",
      "latitude": 54.1670,
      "longitude": -4.4821
    }, {
      "imageURL": targetSVG,
      "title": "Saint Helier",
      "latitude": 49.1919,
      "longitude": -2.1071
    }, {
      "imageURL": targetSVG,
      "title": "Longyearbyen",
      "latitude": 78.2186,
      "longitude": 15.6488
    }]
}, {
  "year": 2012,
  "images": [{
      "imageURL": targetSVG,
      "title": "Bern",
      "latitude": 46.9480,
      "longitude": 7.4481
    }, {
      "imageURL": targetSVG,
      "title": "Kiev",
      "latitude": 50.4422,
      "longitude": 30.5367
    }, {
      "imageURL": targetSVG,
      "title": "London",
      "latitude": 51.5002,
      "longitude": -0.1262
    }, {
      "imageURL": targetSVG,
      "title": "Gibraltar",
      "latitude": 36.1377,
      "longitude": -5.3453
    }, {
      "imageURL": targetSVG,
      "title": "Saint Peter Port",
      "latitude": 49.4660,
      "longitude": -2.5522
    }, {
      "imageURL": targetSVG,
      "title": "Douglas",
      "latitude": 54.1670,
      "longitude": -4.4821
    }, {
      "imageURL": targetSVG,
      "title": "Saint Helier",
      "latitude": 49.1919,
      "longitude": -2.1071
    }, {
      "imageURL": targetSVG,
      "title": "Longyearbyen",
      "latitude": 78.2186,
      "longitude": 15.6488
    }, {
      "imageURL": targetSVG,
      "title": "Kabul",
      "latitude": 34.5155,
      "longitude": 69.1952
    }, {
      "imageURL": targetSVG,
      "title": "Yerevan",
      "latitude": 40.1596,
      "longitude": 44.5090
    }, {
      "imageURL": targetSVG,
      "title": "Baku",
      "latitude": 40.3834,
      "longitude": 49.8932
    }, {
      "imageURL": targetSVG,
      "title": "Manama",
      "latitude": 26.1921,
      "longitude": 50.5354
    }, {
      "imageURL": targetSVG,
      "title": "Dhaka",
      "latitude": 23.7106,
      "longitude": 90.3978
    }, {
      "imageURL": targetSVG,
      "title": "Thimphu",
      "latitude": 27.4405,
      "longitude": 89.6730
    }, {
      "imageURL": targetSVG,
      "title": "Bandar Seri Begawan",
      "latitude": 4.9431,
      "longitude": 114.9425
    }, {
      "imageURL": targetSVG,
      "title": "Phnom Penh",
      "latitude": 11.5434,
      "longitude": 104.8984
    }, {
      "imageURL": targetSVG,
      "title": "Peking",
      "latitude": 39.9056,
      "longitude": 116.3958
    }]
}, {
  "year": 2013,
  "images": [{
      "imageURL": targetSVG,
      "title": "Yerevan",
      "latitude": 40.1596,
      "longitude": 44.5090
    }, {
      "imageURL": targetSVG,
      "title": "Baku",
      "latitude": 40.3834,
      "longitude": 49.8932
    }, {
      "imageURL": targetSVG,
      "title": "Manama",
      "latitude": 26.1921,
      "longitude": 50.5354
    }, {
      "imageURL": targetSVG,
      "title": "Dhaka",
      "latitude": 23.7106,
      "longitude": 90.3978
    }, {
      "imageURL": targetSVG,
      "title": "Thimphu",
      "latitude": 27.4405,
      "longitude": 89.6730
    }, {
      "imageURL": targetSVG,
      "title": "Bandar Seri Begawan",
      "latitude": 4.9431,
      "longitude": 114.9425
    }, {
      "imageURL": targetSVG,
      "title": "Phnom Penh",
      "latitude": 11.5434,
      "longitude": 104.8984
    }, {
      "imageURL": targetSVG,
      "title": "Peking",
      "latitude": 39.9056,
      "longitude": 116.3958
    }, {
      "imageURL": targetSVG,
      "title": "Nicosia",
      "latitude": 35.1676,
      "longitude": 33.3736
    }, {
      "imageURL": targetSVG,
      "title": "T'bilisi",
      "latitude": 41.7010,
      "longitude": 44.7930
    }, {
      "imageURL": targetSVG,
      "title": "New Delhi",
      "latitude": 28.6353,
      "longitude": 77.2250
    }, {
      "imageURL": targetSVG,
      "title": "Jakarta",
      "latitude": -6.1862,
      "longitude": 106.8063
    }, {
      "imageURL": targetSVG,
      "title": "Teheran",
      "latitude": 35.7061,
      "longitude": 51.4358
    }, {
      "imageURL": targetSVG,
      "title": "Baghdad",
      "latitude": 33.3157,
      "longitude": 44.3922
    }, {
      "imageURL": targetSVG,
      "title": "Jerusalem",
      "latitude": 31.76,
      "longitude": 35.17
    }, {
      "imageURL": targetSVG,
      "title": "Tokyo",
      "latitude": 35.6785,
      "longitude": 139.6823
    }, {
      "imageURL": targetSVG,
      "title": "Amman",
      "latitude": 31.9394,
      "longitude": 35.9349
    }]
}, {
  "year": 2014,
  "images": [{
      "imageURL": targetSVG,
      "title": "New Delhi",
      "latitude": 28.6353,
      "longitude": 77.2250
    }, {
      "imageURL": targetSVG,
      "title": "Jakarta",
      "latitude": -6.1862,
      "longitude": 106.8063
    }, {
      "imageURL": targetSVG,
      "title": "Teheran",
      "latitude": 35.7061,
      "longitude": 51.4358
    }, {
      "imageURL": targetSVG,
      "title": "Baghdad",
      "latitude": 33.3157,
      "longitude": 44.3922
    }, {
      "imageURL": targetSVG,
      "title": "Jerusalem",
      "latitude": 31.76,
      "longitude": 35.17
    }, {
      "imageURL": targetSVG,
      "title": "Tokyo",
      "latitude": 35.6785,
      "longitude": 139.6823
    }, {
      "imageURL": targetSVG,
      "title": "Amman",
      "latitude": 31.9394,
      "longitude": 35.9349
    }, {
      "imageURL": targetSVG,
      "title": "Astana",
      "latitude": 51.1796,
      "longitude": 71.4475
    }, {
      "imageURL": targetSVG,
      "title": "Kuwait",
      "latitude": 29.3721,
      "longitude": 47.9824
    }, {
      "imageURL": targetSVG,
      "title": "Bishkek",
      "latitude": 42.8679,
      "longitude": 74.5984
    }, {
      "imageURL": targetSVG,
      "title": "Vientiane",
      "latitude": 17.9689,
      "longitude": 102.6137
    }, {
      "imageURL": targetSVG,
      "title": "Beyrouth / Beirut",
      "latitude": 33.8872,
      "longitude": 35.5134
    }, {
      "imageURL": targetSVG,
      "title": "Kuala Lumpur",
      "latitude": 3.1502,
      "longitude": 101.7077
    }, {
      "imageURL": targetSVG,
      "title": "Ulan Bator",
      "latitude": 47.9138,
      "longitude": 106.9220
    }, {
      "imageURL": targetSVG,
      "title": "Pyinmana",
      "latitude": 19.7378,
      "longitude": 96.2083
    }, {
      "imageURL": targetSVG,
      "title": "Kathmandu",
      "latitude": 27.7058,
      "longitude": 85.3157
    }, {
      "imageURL": targetSVG,
      "title": "Muscat",
      "latitude": 23.6086,
      "longitude": 58.5922
    }]
}, {
  "year": 2015,
  "images": [{
      "imageURL": targetSVG,
      "title": "Vientiane",
      "latitude": 17.9689,
      "longitude": 102.6137
    }, {
      "imageURL": targetSVG,
      "title": "Beyrouth / Beirut",
      "latitude": 33.8872,
      "longitude": 35.5134
    }, {
      "imageURL": targetSVG,
      "title": "Kuala Lumpur",
      "latitude": 3.1502,
      "longitude": 101.7077
    }, {
      "imageURL": targetSVG,
      "title": "Ulan Bator",
      "latitude": 47.9138,
      "longitude": 106.9220
    }, {
      "imageURL": targetSVG,
      "title": "Pyinmana",
      "latitude": 19.7378,
      "longitude": 96.2083
    }, {
      "imageURL": targetSVG,
      "title": "Kathmandu",
      "latitude": 27.7058,
      "longitude": 85.3157
    }, {
      "imageURL": targetSVG,
      "title": "Muscat",
      "latitude": 23.6086,
      "longitude": 58.5922
    }, {
      "imageURL": targetSVG,
      "title": "Islamabad",
      "latitude": 33.6751,
      "longitude": 73.0946
    }, {
      "imageURL": targetSVG,
      "title": "Manila",
      "latitude": 14.5790,
      "longitude": 120.9726
    }, {
      "imageURL": targetSVG,
      "title": "Doha",
      "latitude": 25.2948,
      "longitude": 51.5082
    }, {
      "imageURL": targetSVG,
      "title": "Riyadh",
      "latitude": 24.6748,
      "longitude": 46.6977
    }, {
      "imageURL": targetSVG,
      "title": "Singapore",
      "latitude": 1.2894,
      "longitude": 103.8500
    }, {
      "imageURL": targetSVG,
      "title": "Seoul",
      "latitude": 37.5139,
      "longitude": 126.9828
    }, {
      "imageURL": targetSVG,
      "title": "Colombo",
      "latitude": 6.9155,
      "longitude": 79.8572
    }, {
      "imageURL": targetSVG,
      "title": "Damascus",
      "latitude": 33.5158,
      "longitude": 36.2939
    }, {
      "imageURL": targetSVG,
      "title": "Taipei",
      "latitude": 25.0338,
      "longitude": 121.5645
    }, {
      "imageURL": targetSVG,
      "title": "Dushanbe",
      "latitude": 38.5737,
      "longitude": 68.7738
    }]
}, {
  "year": 2016,
  "images": [{
      "imageURL": targetSVG,
      "title": "Riyadh",
      "latitude": 24.6748,
      "longitude": 46.6977
    }, {
      "imageURL": targetSVG,
      "title": "Singapore",
      "latitude": 1.2894,
      "longitude": 103.8500
    }, {
      "imageURL": targetSVG,
      "title": "Seoul",
      "latitude": 37.5139,
      "longitude": 126.9828
    }, {
      "imageURL": targetSVG,
      "title": "Colombo",
      "latitude": 6.9155,
      "longitude": 79.8572
    }, {
      "imageURL": targetSVG,
      "title": "Damascus",
      "latitude": 33.5158,
      "longitude": 36.2939
    }, {
      "imageURL": targetSVG,
      "title": "Taipei",
      "latitude": 25.0338,
      "longitude": 121.5645
    }, {
      "imageURL": targetSVG,
      "title": "Dushanbe",
      "latitude": 38.5737,
      "longitude": 68.7738
    }, {
      "imageURL": targetSVG,
      "title": "Bangkok",
      "latitude": 13.7573,
      "longitude": 100.5020
    }, {
      "imageURL": targetSVG,
      "title": "Dili",
      "latitude": -8.5662,
      "longitude": 125.5880
    }, {
      "imageURL": targetSVG,
      "title": "Ankara",
      "latitude": 39.9439,
      "longitude": 32.8560
    }, {
      "imageURL": targetSVG,
      "title": "Ashgabat",
      "latitude": 37.9509,
      "longitude": 58.3794
    }, {
      "imageURL": targetSVG,
      "title": "Abu Dhabi",
      "latitude": 24.4764,
      "longitude": 54.3705
    }, {
      "imageURL": targetSVG,
      "title": "Tashkent",
      "latitude": 41.3193,
      "longitude": 69.2481
    }, {
      "imageURL": targetSVG,
      "title": "Hanoi",
      "latitude": 21.0341,
      "longitude": 105.8372
    }, {
      "imageURL": targetSVG,
      "title": "Sanaa",
      "latitude": 15.3556,
      "longitude": 44.2081
    }, {
      "imageURL": targetSVG,
      "title": "Buenos Aires",
      "latitude": -34.6118,
      "longitude": -58.4173
    }, {
      "imageURL": targetSVG,
      "title": "Bridgetown",
      "latitude": 13.0935,
      "longitude": -59.6105
    }, {
      "imageURL": targetSVG,
      "title": "Belmopan",
      "latitude": 17.2534,
      "longitude": -88.7713
    }]
} ];




/*map set up*/
var map = AmCharts.makeChart( "chartdiv", {
  "type": "map",
  "projection": "miller",
  
  "imagesSettings": {
    "rollOverColor": "#089282",
    "rollOverScale": 3,
    "selectedScale": 3,
    "selectedColor": "#089282",
    "color": "#fff"
  },
  "dataProvider": {
    "map": "worldLow",
    "images": markers[0].images,
    
  },
  
  
  "zoomControl": {
		"zoomControlEnabled": false

	},
  

  "areasSettings": {
    "unlistedAreasColor": "#a1d292"
  },
  
  "listeners": [{
    "event": "init",
    "method": function(e) {

      // init jQuery UI Slider source:https://www.amcharts.com/kbase/time-line-map-jquery-ui-slider/
      $( "#slider" ).slider({
        "min": 0,
        "max": (markers.length - 1),
        "create": function( event, ui ) {
          var dataSet = markers[0];
          $("#slider .ui-slider-handle").text(dataSet.year);
        },
        "slide": function( event, ui ) {
          var dataSet = markers[ui.value];
          e.chart.dataProvider.images = dataSet.images;
          e.chart.validateData();
          $(ui.handle).text(dataSet.year);
        }
      });
    }
  }]
} );